### PR TITLE
Use `@timeit` on function calls

### LINKED ISSUE #934: Try using `@timeit to` on function calls, not on `begin ... end` blocks
### Description

When an error happens inside the `begin ... end` block, the`@timeit` macro will hide the line where the error happened by just saying that the error happens at the macro line, and they listing `macro expansion` errors - which is unhelpful

### PR DESCRIPTION
**Pull request by gnawin**
## Related issues

Closes #934 

- Remove EnergyProblem.timings
- Use `@timeit` on function calls

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/main/docs/src/90-contributing.md)

- [x] Tests are passing
- [x] Lint workflow is passing
- [ ] Docs were updated and workflow is passing

### CODE REVIEW

**Review by abelsiqueira — APPROVED** [review]
LGTM, thanks @gnawin !

**Comment by gnawin** [comment]
@abelsiqueira @datejada After checking the time log [log.txt](https://github.com/user-attachments/files/18078212/log.txt) for the Tiny case, here are a few observations:
- `create_interna_structures` is 27.6% of the time, which seems mostly spent on the functions related to reading tables (e.g., `TulipaIO.get_table`, `DBInterface.execute`). Probably there is nothing we can do better, but interesting to see.
- `compute_dual_variables ` is 3 times more expensive than `total solver time`. Seeing the code, it makes sense, but still, good to realize.

**Comment by abelsiqueira** [comment]
Nice insights. We should definitely do that as part of the efficiency improvement for the EU dataset

**Comment by datejada** [comment]
Thanks @gnawin; the compute duals will change once we change how to store the solution and hopefully, it will be faster than the current approach 😄

**Pull request merged**
