### PR TITLE
[WIP] Add ESDL XML reader

### LINKED ISSUE #89: Map ESDL to a Julia data structure (assets data, flows data, and graph)
Go through the ESDL file and map ports to connections to create a graph in Julia.

The esdl ports link to a hash that later must be scanned to find the right connection.

Also, obtain the assets and flows data

---
Removed the following because this will happen before GML+CSV are created, i.e., before Julia is involved.
~Possible implementation~
- ~represent graph data structure using [GraphIO.jl](https://github.com/JuliaGraphs/GraphIO.jl)~

### PR DESCRIPTION
**Pull request by sjvrijn**
# Pull request details

## Describe the changes made in this pull request

Writing a reader to take an ESDL/XML file and turn it into a Julia graph for further internal usage

## List of related issues or pull requests

Closes #89

## Collaboration confirmation

As a contributor I confirm

- [ ] I read and followed the instructions in README.dev.md
- [ ] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [ ] Tests are passing
- [ ] Lint is passing

### CODE REVIEW

**Comment by clizbe** [comment]
This may be unneeded if we use a JSON instead.

**Comment by clizbe** [comment]
@suvayu If we've decided to use JSON, can we close this PR?

**Comment by suvayu** [comment]
I'ld like to leave this open until we also get the other attributes

**Comment by clizbe** [comment]
@suvayu Can we close it now? 🙃

**Comment by suvayu** [comment]
sorry, forgot about this alternative.  I'll close it

**Pull request closed without merging**
