### PR TITLE
Test Norse with Cbc and GLPK and conditionally with SCIP

### LINKED ISSUE #378: [BUG] SCIP doesn't work on Windows so testing fails
### Description

#377 introduced SCIP in the tests, but apparently it doesn't work on Windows:

https://github.com/TulipaEnergy/TulipaEnergyModel.jl/actions/runs/7386730638/job/20093938798#step:6:39

Best solution would be finding another open source solver good enough for the tests. Maybe Cbc or GLPK will handle it.

### Reproduction steps

```bash
See actions: https://github.com/TulipaEnergy/TulipaEnergyModel.jl/actions/runs/7386730638/job/20093938798#step:6:39
```

### Logs

_No response_

### OS

Windows

### PR DESCRIPTION
**Pull request by abelsiqueira**
# Pull request details

## Describe the changes made in this pull request

Remove SCIP.
Test Norse with Cbc and GLPK as well.

## List of related issues or pull requests

Closes #378 

## Collaboration confirmation

As a contributor I confirm

- [x] I read and followed the instructions in README.dev.md
- [x] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [x] Tests are passing
- [x] Lint is passing

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Needs to be rebased after #379

**Comment by datejada** [comment]
Hi @abelsiqueira,

Cbc and GLPK are good enough for the testing in the GitHub actions. It is a pity that SCIP can't be used for testing in Windows. Is it possible to set up the GitHub action to test SCIP only for Linux and Mac?

**Comment by abelsiqueira** [comment]
It is possible, but it would be a bit ugly. Something like:

- Create a EXTRA_SOLVERS environment variable in the actions storing the package/solver pairs.
- Install the packages in the action
- In the test code, get the packages and `using` them
- In the test code, get the solvers and loop through them

It would change things in four places, so I would not recommend just to test SCIP.
However, it might be useful in the future to also run tests on the server/remote machine that has the proprietary solvers, and in that case we might want to run the tests with the proprietary solvers as well. Assuming it will be a Linux machine, we can also test SCIP.
If that is feasible, we can create an issue for that.

**Comment by datejada** [comment]
Great! Thanks for the explanation. Having the option of testing on "server/remote machine that has the proprietary solvers" is good for the future since we will use Xpress, and then we also might want to test that using one of our machines. So, let's go forward without SCIP and use Cbc and GLPK instead.

**Review by datejada — APPROVED** [review]
LGTM

**Pull request merged**
