### PR TITLE
Remove graph dependency from src/constraints/consumer.jl

### LINKED ISSUE #943: Don't get data from graph object in src/constraints/consumer.jl

### PR DESCRIPTION
**Pull request by abelsiqueira**
Part of #942
Closes #943

### CODE REVIEW

**Comment by abelsiqueira** [comment]
@datejada, I've updated this to follow the new strategy. The code is still slow, though, so we might want to wait until all rep_periods_profiles are removed to see if it's possible to make it better.

**Comment by abelsiqueira** [comment]
@datejada and I evaluated the 3 options (1-Using graph, 2-Using full DuckDB, which is the version from 2 weeks ago, and 3-Using the new profiles object). Here are the results:

```
Option 1 - Using graph[a].profiles_rep_periods

(1/1) benchmarking "energy_problem"...
  (1/2) benchmarking "input_and_constructor"...
  done (took 29.587801709 seconds)
  (2/2) benchmarking "create_model"...
  done (took 139.582342084 seconds)
done (took 172.174956 seconds)
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "energy_problem" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "input_and_constructor" => Trial(6.525 s)
          "create_model" => Trial(33.750 s)


Option 2 - Remove graph[a].profiles_rep_periods and compute aggregation with DuckDB

(1/1) benchmarking "energy_problem"...
  (1/2) benchmarking "input_and_constructor"...
  done (took 28.673210792 seconds)
  (2/2) benchmarking "create_model"...
  done (took 144.815846917 seconds)
done (took 175.86473875 seconds)
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "energy_problem" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "input_and_constructor" => Trial(6.508 s)
          "create_model" => Trial(34.858 s)


Option 3 - Change graph[a].profiles_rep_periods[...] to get profile_name with DuckDB and create profiles structure

(1/1) benchmarking "energy_problem"...
  (1/2) benchmarking "input_and_constructor"...
  done (took 34.309520792 seconds)
  (2/2) benchmarking "create_model"...
  done (took 127.688325292 seconds)
done (took 164.306446625 seconds)
1-element BenchmarkTools.BenchmarkGroup:
  tags: []
  "energy_problem" => 2-element BenchmarkTools.BenchmarkGroup:
          tags: []
          "input_and_constructor" => Trial(7.747 s)
          "create_model" => Trial(30.999 s)

```

Option 3 was a bit faster, and should be reasonable to maintain, so we're using it for now

**Comment by abelsiqueira** [comment]
For future reference, this is the DuckDB query to join and aggregate the profiles (option 2):

```sql
         SELECT
             cons.*,
             ANY_VALUE(asset.type) AS type,
             ANY_VALUE(asset.consumer_balance_sense) AS consumer_balance_sense,
             ANY_VALUE(asset_milestone.peak_demand) AS peak_demand,
             COALESCE(MEAN(profile.value), 1) AS demand_agg
         FROM $cons AS cons
         LEFT JOIN asset
             ON cons.asset = asset.asset
         LEFT JOIN asset_milestone
             ON cons.asset = asset_milestone.asset
             AND cons.year = asset_milestone.milestone_year
         LEFT JOIN assets_profiles
             ON cons.asset = assets_profiles.asset
             AND cons.year = assets_profiles.commission_year
             AND assets_profiles.profile_type = 'demand'
         LEFT JOIN profiles_rep_periods AS profile
             ON profile.profile_name = assets_profiles.profile_name
             AND cons.year = profile.year
             AND cons.rep_period = profile.rep_period
             AND cons.time_block_start <= profile.timestep
             AND profile.timestep <= cons.time_block_end
         GROUP BY cons.*
         ORDER BY cons.index -- order is important
         
```

**Review by datejada — APPROVED** [review]
Reviewed during an online meeting

**Pull request merged**
