### PR TITLE
Create model discount parameters

### LINKED ISSUE #802: Create economic parameters
Create structure to hold model parameters
Structure should be inside EnergyProblem
Should be read after `connection` is created because we need the data to define defaults.
Either create at `EnergyProblem` constructor or `create_model!`.

### PR DESCRIPTION
**Pull request by gnawin**
# Pull request details

## Describe the changes made in this pull request

- create a toml file for data on the model level (should be scenario data in the future) only for multi-year
- this file is directly read in `create_model`. Note this means all other cases will use this toml. The discount year will matter to other test cases. Since all other cases have a year of 2030, making a discount year of 2030 would mean doing nothing.
- the generalization of this data and separation of model data and scenario data should be done in the refactor #701 (under _AND THEN_)    

## List of related issues or pull requests

Closes #802 

## Collaboration confirmation

As a contributor I confirm

-   [x] I read and followed the instructions in README.dev.md
-   [ ] The documentation is up to date with the changes introduced in this Pull Request (or NA)
-   [x] Tests are passing
-   [x] Lint is passing

### CODE REVIEW

**Comment by gnawin** [comment]
Hi both @abelsiqueira @datejada, I have this draft PR to hear your opinions. 

The idea is to create two parameters that apply to the model, i.e., which do not depend on the assets. Since we currently don't have a place for that, I just put them in graph-assets-data. Do you think there is a better way to do it now? 

For example, I thought about creating a new file. But since my references are the current files, which look differently from this potential file (just two names with two parameters), I don't yet see a straightforward way to do it.

**Comment by datejada** [comment]
> Hi both @abelsiqueira @datejada, I have this draft PR to hear your opinions.
> 
> The idea is to create two parameters that apply to the model, i.e., which do not depend on the assets. Since we currently don't have a place for that, I just put them in graph-assets-data. Do you think there is a better way to do it now?
> 
> For example, I thought about creating a new file. But since my references are the current files, which look differently from this potential file (just two names with two parameters), I don't yet see a straightforward way to do it.

This proposal is not ideal, we will repeat values unnecessarily. I was looking for inspiration in other models and this data is normally stored in a new entity/file/table with the model properties/constants/parameters.

What is the best way to go forward in Tulipa? I am not sure, but I am leaning toward a separate file (CSV, TOML, YAML, or JSON) to store this information and any other constant that we might want to define or need in the model.

**Comment by abelsiqueira** [comment]
I agree, this should be a separate file. I recommend using TOML:

```toml
model_discount_rate = 0.03
model_discount_year = 2020
```

Since these are parameters, not data, it makes sense that they have a different, simpler, format. Also, that they will be manage outside of TulipaIO.

**Comment by gnawin** [comment]
Thank you both @datejada @abelsiqueira. 

I created a toml file. Since it is outside TulipaIO, so I suppose it's not part of the connection (which currently is tied to `read_csv` in TulipaIO), but rather something else. For that I added an extra argument in `io.jl`. Note that this extra argument will need to added to lots of other places. 

I just want to check with you if this is fine before I make changes accordingly.

**Comment by abelsiqueira** [comment]
It is not part of the connection. Some questions before judging how to handle it:

- Is the file mandatory? Do you need it in all uses of Tulipa? If you don't have one, is there a reasonable default for the parameters?
- Where do you begin to need these parameters? Which function?
- Is it part of the EnergyProblem? Does it make sense to keep these parameters inside it?

**Comment by gnawin** [comment]
@abelsiqueira thanks for thinking along

**Comment by abelsiqueira** [comment]
If it's planned as a temporary solution, I would just open the file directly in `create_model!` and then we discuss these questions in more details later.
Also, I would suggest not creating the file for every test/input, since it's only necessary for multi-year. This way you ensure you're not making it necessary.
Also, it's good to add to #701 to remember that we have to change it afterwards.

**Comment by gnawin** [comment]
@abelsiqueira I made the changes accordingly, but read in the data in create_model instead of create_model!, this way I don't have to add additional arguments for now.

**Review by abelsiqueira — CHANGES_REQUESTED** [review]
That's too hard-coded. It's not conditional on the problem, so it is reading the parameters for all inputs, not only the multi-year. Furthermore, it is reading a fixed file, which is the same as explicitly defining the variables in the file (i.e., hard-code them).
My thinking was you give the file as argument to `create_model`. If nothing is passed, you don't open anything. You would still need to change a few places, but you don't carry anything around.

If you need a quick hack to continue other PRs, you might as well just explicitly define `model_discount_rate` and `model_discount_year` in the `create_model!` function. But then it might be more useful to do it in the specific PR, than do it here.

What is the goal of #802? Enable reading model parameters for general use? Or just create these two parameters somewhere? Or something else, maybe? What is it blocking?

**Comment by gnawin** [comment]
Closed in favor of #813.

**Pull request closed without merging**
