### PR TITLE
Specify the domain of decommission variables

### LINKED ISSUE #828: Add checks to the domain of decommission variables and make sure they only exist when there are existing capacities or investments - compact method.
~This should avoid making the multi-year case study unbounded~ (see #831)

Best to alter the structure of code as little as possible (so #833 is not a good way to go), but allow more repetitions if needed.

### PR DESCRIPTION
**Pull request by gnawin**
# Pull request details

## List of related issues or pull requests

Closes #828 

## Collaboration confirmation

As a contributor I confirm

-   [ ] I read and followed the instructions in README.dev.md
-   [ ] The documentation is up to date with the changes introduced in this Pull Request (or NA)
-   [ ] Tests are passing
-   [ ] Lint is passing

### CODE REVIEW

**Comment by gnawin** [comment]
@abelsiqueira @datejada It is more or less straightforward to do this for the decommission variable of the compact method, so I did this before the refactor. 

The simple method is a bit more complex because it is indexed differently, i.e., not using an indice set yet, but it will be the same idea (and the conditions are very similar as well). Since we'll refactor, I did not do it for the simple method and rather do it in the factor.

**Comment by gnawin** [comment]
@abelsiqueira both the link and the codecov/project fails are confusing to me, could you have a look? Thanks!

**Comment by abelsiqueira** [comment]
For completeness, repeating some thigns from the chat here.

The link check failure is probably due to changes in the treatment of automated link checkers by the end points. Recommended solution is to ignore at the moment, and check after we apply Bestie (#676). If the error persists we can add it to the ignore list. This is safe to do for this website at least. We can think again for the others. 
On a side note, it is actually possible to add it to the ignore list at `.markdown-link-check.json` right now, but we would need to go check how to run it locally

The Codecov error is probably because version "1" points to "1.11" now (https://github.com/JuliaLang/www.julialang.org/pull/2160) and that affected how the coverage is processed.
Possible solutions:
- Set a range of acceptable coverage instead of the 100% goal - it will be harder and harder to keep it at 100%, so this might be an incentive and the right time to do it
- Change the `for` and remove the intermediary variable `constraints_files`.

**Review by abelsiqueira — APPROVED** [review]
LGTM

**Comment by gnawin** [comment]
> For completeness, repeating some thigns from the chat here.
> 
> The link check failure is probably due to changes in the treatment of automated link checkers by the end points. Recommended solution is to ignore at the moment, and check after we apply Bestie (#676). If the error persists we can add it to the ignore list. This is safe to do for this website at least. We can think again for the others. On a side note, it is actually possible to add it to the ignore list at `.markdown-link-check.json` right now, but we would need to go check how to run it locally
> 
> The Codecov error is probably because version "1" points to "1.11" now ([JuliaLang/www.julialang.org#2160](https://github.com/JuliaLang/www.julialang.org/pull/2160)) and that affected how the coverage is processed. Possible solutions:
> 
> * Set a range of acceptable coverage instead of the 100% goal - it will be harder and harder to keep it at 100%, so this might be an incentive and the right time to do it
> * Change the `for` and remove the intermediary variable `constraints_files`.

After some searching, it seems that I have to use an inline comment, but it does not work 
```
<!-- markdownlint-disable-next-line -->
[Visit this link](https://code.visualstudio.com)
```
Is this what I should do?

**Pull request merged**
