### PR TITLE
Create Multi-year Investments test data

### LINKED ISSUE #758: Create multi-year test data
@gnawin, this is to keep track of the Multi-year data discussion.

After #757, we have a proper new structure for data, but since things are moving fast, that might change before we finish this issue. Let's try to add this data separately, so it doesn't become part of the issue. So let's try to make a script that generates the data from some of the existing input - with something else external, if necessary.

- Is the Multi-year data generated from any of the other files?
- Is there external data that is being added (e.g., another profile)
- Can we create a high-level script/description of how to write the multi-year data?
  - E.g., "take the Tiny data, copy all rows from assets-data but change the year to 2050. Then ..."

### LINKED ISSUE #759: Update structures with year information and update the tests to use the multi-year test data

### PR DESCRIPTION
**Pull request by abelsiqueira**
Create utils/scripts/create-multiyear-data.jl to create this data.
This will be used by the next PR to implement multiyear input.

The data is created by copying the Tiny data, duplicating rows, and changing
the year of the duplicates.
The following files have been created:

Remarks:

- Flows are **not** automatically active in 2050 if the assets are active, so the duplication of rows happened for both `assets-data.csv` and `flows-data.csv`.
- The `year` is informed in both `*-profiles.csv` and `profiles-rep-periods`. The `profile_name` and `year` should be used to determine the used profile.

# Pull request details

## List of related issues or pull requests

Closes #758

## Collaboration confirmation

As a contributor I confirm

-   [x] I read and followed the instructions in README.dev.md
-   [x] The documentation is up to date with the changes introduced in this Pull Request (or NA)
-   [x] Tests are passing
-   [x] Lint is passing

### CODE REVIEW

**Comment by datejada** [comment]
@abelsiqueira Thanks for the PR. I have no comments, but I would wait until @gnawin review it to marge the changes since he has the broader picture of the multi-year development.

**Comment by gnawin** [comment]
@abelsiqueira Thanks a lot. It looks good to me. I just got a bit confused by the use of  `active` regarding your remark
> Flows are not automatically active in 2050 if the assets are active, so the duplication of rows happened for both assets-data.csv and flows-data.csv.
Because I see the last row of the two files have been set to `false` in `active`. Could you clarify a bit?

**Comment by abelsiqueira** [comment]
What I meant is that it is not sufficient to have assets exists in 2050. The flows must be defined in 2050 as well. And consequently, being active depends on that value.
In the future, it could make sense to automatically create the flows and mark them as active if they exist in a previous year, or based on lifetime, and/or assets being active.
I did not add any of that, so for now you have to make everything explicit.

**Review by gnawin — APPROVED** [review]
Thanks! LGTM.

**Pull request merged**
