### PR TITLE
Add optimization problem size info to the display of `EnergyProblem`

### LINKED ISSUE #510: Show more solver info in `run_scenario`
### What and Why

`run_scenario` does not include solver log such as the number of constraints, variables and solving status, which can be inconvenient. Or to add this info to the display of `EnergyProblem`.

JuMP has functions to display the number of variables and constraints (https://jump.dev/JuMP.jl/stable/api/JuMP/#num_constraints). The easiest solution is to add this info to the display.

### Possible Drawbacks

_No response_

### Related Issues

_No response_

### PR DESCRIPTION
**Pull request by gnawin**
# Pull request details

## Describe the changes made in this pull request

Add more outputs to the display of `EnergyProblem`

## List of related issues or pull requests

Closes #510 

## Collaboration confirmation

As a contributor I confirm

- [x] I read and followed the instructions in README.dev.md
- [x] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [x] Tests are passing
- [x] Lint is passing

### CODE REVIEW

**Review by datejada — CHANGES_REQUESTED** [review]
Thanks @gnawin. There are two comments:

1. Since there are several `!isnothing(ep.model)` it is better to have an if statement at the start of the function and only print the relevant information for each case. For example, if it is not solved, only show the "Model created". If you solve the model, then you show all the numbers. This will be it; you don't need to check for each line if the model is nothing.
2. instead of having the number of constraints including the bounds, please print the number of bounds, which is the difference between the values you currently have.

Thanks!

**Comment by gnawin** [comment]
Thank you for the comments @datejada. Before I make further changes, I have one doubt though. Adding if statements to check the cases (e.g., model created, model solved) will make the display neater, but the code will be more repetitive, i.e., you put largely similar codes under each if-else block. 

In summary, either you print all the info, the display will be less neat but the code will be more compact, or you print for each case, the display will be neater but the code will be less compact. Do we want to opt for the latter? Or is there a 3rd way of implementation?

**Comment by datejada** [comment]
Hi @gnawin, @abelsiqueira and I commented that we want to avoid printing NaN since the model has yet to be solved. So, that is the idea behind the first point. You should only print your information and avoid NaN, empty, etc. Does that make sense?

**Comment by gnawin** [comment]
Hi @datejada @abelsiqueira, thanks for the clarification. 

Yes, that makes total sense. I was hesitating because I felt that as a result of not printing NaN, the code would be less compact. But after the latest implementation, I think it looks okay.

**Comment by datejada** [comment]
Great! Thanks, we are almost there. I agree with all the changes, but the codecov is still complaining because it was not triggered with your last commit. Something similar happened to Abel on Monday, he manage to trigger it again by rebasing the branch and pushing again. Could you try that? if we make the codecov happy in te PR, then we can merge 😃

**Comment by gnawin** [comment]
@datejada Great! I did that and now codecov is happy 😄 .

**Review by datejada — APPROVED** [review]
Awesome! Thanks

**Pull request merged**
