### PR TITLE
Custom command to run benchmark workflow from a PR

### PR DESCRIPTION
**Pull request by abelsiqueira**
# Pull request details

## Describe the changes made in this pull request

Temporarily removes the benchmark workflow.
It will only run when manually request (which won't be useful, since the results won't be posted).

## List of related issues or pull requests

Related:
- #59 (does not close it)

## Collaboration confirmation

As a contributor I confirm

- [x] I read and followed the instructions in README.dev.md
- [x] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [x] Tests are passing
- [x] Lint is passing

### CODE REVIEW

**Comment by suvayu** [comment]
You can see this in action in [this repo](https://github.com/suvayu/fictional-giggle/pull/5). If you add a comment with `/run-benchmark`, it will trigger the workflow, and respond with a comment containing the results. In the example repo, there's nothing to benchmark, so it just responds with the latest commit of the PR branch (this way you also know the correct version is being "benchmarked").

**Comment by suvayu** [comment]
@abelsiqueira I can't tag you as reviewer, maybe because you opened this PR.

**Comment by abelsiqueira** [comment]
> @abelsiqueira I can't tag you as reviewer, maybe because you opened this PR.

Indeed. Also, I prefer that you don't commit on top of my branch, I find it too intrusive.
Since I can't review it, and it's your commit, I will close this, you make a PR, and I review that.

**Comment by abelsiqueira** [comment]
Closed in favor of #80

**Pull request closed without merging**
