### PR TITLE
Update the authors list in various files

### PR DESCRIPTION
**Pull request by abelsiqueira**
Update the authors list.
Move some people to the new all contributors (will be done in the comments in the PR)

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/main/docs/src/90-contributing.md)
- [x] Tests are passing
- [x] Lint workflow is passing
- [x] Docs were updated and workflow is passing

### CODE REVIEW

**Review by datejada — APPROVED** [review]
LGTM

**Comment by abelsiqueira** [comment]
@all-contributors please add @abelsiqueira for code

**Comment by abelsiqueira** [comment]
@all-contributors please add @abelsiqueira for code, review. ideas

**Comment by abelsiqueira** [comment]
@all-contributors please add @datejada for code, review, ideas, research

**Comment by abelsiqueira** [comment]
@all-contributors please add @suvayu for code, review, ideas

**Comment by abelsiqueira** [comment]
@all-contributors please add @gnawin for code, review, ideas, research

**Comment by abelsiqueira** [comment]
@all-contributors please add @clizbe for code, review, ideas, projectManagement

**Comment by abelsiqueira** [comment]
@all-contributors please add @g-moralesespana for research, ideas, fundingFinding, projectManagement

**Comment by abelsiqueira** [comment]
@all-contributors please add @jkiviluo for ideas, research

**Comment by abelsiqueira** [comment]
@all-contributors please add @mdeweerdt for fundingFinding, projectManagement

**Comment by abelsiqueira** [comment]
@all-contributors please add @greg-neustroev for ideas, research, code

**Comment by abelsiqueira** [comment]
@all-contributors please add @gzclarence for ideas, research

**Comment by abelsiqueira** [comment]
@all-contributors please add @lsoucasse for ideas

**Comment by abelsiqueira** [comment]
@all-contributors please add @sjvrijn for ideas

**Comment by datejada** [comment]
@all-contributors please add @maaikeelgersma for ideas, and research.

**Pull request merged**
