### PR TITLE
Restructure the code to have both long- and short-term storage

### LINKED ISSUE #255: Add linked-representative days formulation for seasonal (long-term) storage
### What and Why

This is one of the core features of the model. It is based on the following formulation:

https://ieeexplore.ieee.org/abstract/document/8334256

We need to translate this to the current formulation of Tulipa.

### Possible Drawbacks

We need more input data and possibly a new file.

Also, @abelsiqueira, I need your help to tackle these changes (maybe we can use the same logic of ranges to simply the proposed formulation in the paper)

### Related Issues

- [x] #455 
- [x] #456
- [x] #509
- [x] #512
- [x] #516
- [x] #522
- [x] #523
- [x] #514
- [x] #549
- [x] #458 
- [x] TulipaEnergy/TulipaPlots.jl/issues/15

### PR DESCRIPTION
**Pull request by datejada**
# Pull request details

## Describe the changes made in this pull request

Changes in the code and input data to consider both long- and short-term storage. These changes allow including the linked-representative periods in the model.

## List of related issues or pull requests

Closes #255

## Collaboration confirmation

As a contributor I confirm

- [x] I read and followed the instructions in README.dev.md
- [ ] The documentation is up to date with the changes introduced in this Pull Request (or NA)
- [x] Tests are passing
- [x] Lint is passing

### CODE REVIEW

**Comment by datejada** [comment]
@abelsiqueira I have implemented the constraints we need here before, but in the "old" style, i.e., matrices. So, I would appreciate your help implementing them using the ranges approach. We can do this in one of the following working sessions. I'll do as much as I can in the meantime.

**Comment by abelsiqueira** [comment]
@datejada, it is clear to me how the equations work. The new set `X`, in particular. It might be better to discuss next week in the afternoon.

**Comment by datejada** [comment]
Yes, it is better to do it in person. Thanks!

**Comment by datejada** [comment]
We close this PR in favour of #446

**Pull request closed without merging**
