### PR TITLE
Update EU benchmark files

### LINKED ISSUE #112: Create a simple European case study for testing
Create the esdl file and fill with data for the simple European case study.

### LINKED ISSUE #426: Update western EU case to use 123 resolution
### What and Why

Update input CSV data files for the EU case study to test speed and benchmark the model

### Possible Drawbacks

_No response_

### Related Issues

_No response_

### PR DESCRIPTION
**Pull request by datejada**
# Pull request details

## Describe the changes made in this pull request

Update the files for the large-scale EU case study for benchmark purposes.

## List of related issues or pull requests

Closes #112
Closes #426

## Collaboration confirmation

As a contributor I confirm

-   [x] I read and followed the instructions in README.dev.md
-   [NA] The documentation is up to date with the changes introduced in this Pull Request (or NA)
-   [x] Tests are passing
-   [x] Lint is passing

### CODE REVIEW

**Comment by datejada** [comment]
I have the same problem with the benchmark as @gnawin in PR #582. So, let's wait until Abel returns from holiday to see what is happening here.

**Comment by datejada** [comment]
With these updated input data files for the EU case study, we get the following stats:

- read data: 80s and 5.6GB of memory allocated
- create model: 2081s and 86GB of memory allocated
- solve model (HiGHS): 2.3h and 11GB of memory allocated

**Comment by datejada** [comment]
@abelsiqueira, I wonder if the benchmark results here are useful since they seem to use data from the main branch. Anyway, we can merge it since it is going to be that data that is useful to improve memory usage in the future. What do you think?

**Review by abelsiqueira — APPROVED** [review]
The benchmark results indeed don't seem to be useful. I'm merging this.

**Pull request merged**
