### PR TITLE
Refactor group constraints to improve performance

### LINKED ISSUE #789: Update group constraints according to the investment methods
The group feature needs an update after the changes in the investment methods for the multi-year investment.

Blocked by: #786 and #783

### PR DESCRIPTION
**Pull request by datejada**
# Pull request details

## Describe the changes made in this pull request

The constraints do not change with the multi-year investment since they are meant to limit the investments that you can make each year rather than limiting the accumulated investments.

The changes here clarify this in the documentation and improve the code's performance.

## List of related issues or pull requests

Closes #789 

## Collaboration confirmation

As a contributor I confirm

-   [x] I read and followed the instructions in README.dev.md
-   [x] The documentation is up to date with the changes introduced in this Pull Request (or NA)
-   [x] Tests are passing
-   [x] Lint is passing

### CODE REVIEW

**Comment by abelsiqueira** [comment]
The error in the benchmark run should be fixed after changing `actions/upload-artifact` to use version `4` in the `.github/workflows/benchmark.yml`.

**Comment by datejada** [comment]
@abelsiqueira The benchmark is complaining about a deprecated version. If you show how to update it I can fix that 😄 

I want to run the benchmark in the EU case study because the changes improve the performance of the group constraint. I ran the benchmarks locally in the Norse case, and I got the following:

**Main**: 
- Time for  creating the model (in seconds): 235.7008262

Value of three runs, so avg. 78.6 seconds

**This branch**
- Time for  creating the model (in seconds): 212.0622996

Value of three runs, so avg. 70.7 seconds

**Comment by datejada** [comment]
@abelsiqueira For the EU, there is not much impact, which is expected since there are no groups in that case, and we get a reduction in the time for the Norse, which has groups. So, I think all seems good with the changes.

**Review by abelsiqueira — APPROVED** [review]
Thanks. Indeed, it doesn't change much because this part is small in comparison.
Also, the problematic `if` is only the first one in line 17 (inside the `sum` in the `@expression`). The other ones are "normal" ifs. This should still be more efficient, but it is not as terrible as `if`s inside `@expression`s.

**Pull request merged**
